### ISSUE TITLE
Adicionando OrElseThrow nos optionals

### ISSUE THREAD

**Issue by arthurs159** [SannyHL/sistema_para_controle_guarda_objetos#1]
Oi Sanny, Olhando seu projeto pude perceber que você utiliza muito o if no caso dos optionals, acredito que você poderia utilizar na linha do seu optional mesmo o OrElseThrow passando o  `new ResponseStatusException(HttpStatus.NOT_FOUND)` ali, e deixando assim sem necessidade de sempre colocar o if com o isPresent no seu código.

**Comment by SannyHL** [comment]
Olá Arthur! Muito obrigada pelo feedback! Vou me atentar em projetos próximos.🌟
